version: '3'
services:
  app:
    container_name: e-commerce-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_LIFETIME=${JWT_LIFETIME}
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
    command: ["npm","run","start" ]
